Gvm/Controllers/DocumentsController.cs
using System;
using System.Collections.ObjectModel;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Gvm.Infra;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNet.Identity;
using Turkok.Core.Caching;
using Turkok.Core.Extensions;
using Turkok.Core.Repository;
using Turkok.Core.Service;
using Turkok.Core.Settings;
using Turkok.Model;
using Turkok.Model.FineUploader;

namespace Gvm.Controllers
{
    public class DocumentsController : MController
    {
        private readonly ICacheManager<int, Document> _cache;
        private readonly IRepository<Document> _repository;
        private readonly IApplicationSettings _settings;
        private readonly IUserService _userService;

        public DocumentsController(
            IUserService userService,
            IApplicationSettings appSettings,
            IRepository<Document> repository,
            ICacheManager<int, Document> cache)
        {
            _repository = repository;
            _cache = cache;
            _settings = appSettings;
            _userService = userService;
        }

        [Audit]
        public ActionResult Index(int? page)
        {
            return View();
        }

        [Audit]
        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            IOrderedQueryable<Document> documents = _repository.Table().Where(x => x.IsDeleted == false).OrderByDescending(x => x.Id);

            return Json(documents.ToDataSourceResult(request));
        }

        [Audit]
        public ActionResult View(int? id)
        {
            if (id.HasValue == false)
            {
                return HttpNotFound();
            }

            Document presentation = _cache.Get(id.Value);

            if (presentation == null)
            {
                presentation = _repository.Table().Include(a => a.Attachments).FirstOrDefault(i => i.Id == id.Value);

                if (presentation == null)
                {
                    return HttpNotFound();
                }

                _cache.Set(id.Value, presentation);
            } 
            return View(presentation);
        }

        [Audit]
        public ActionResult Create()
        {
            return View();
        }
          
        [Audit]
        [HttpPost]
        public ActionResult Create(Document document)
        {
            if (ModelState.IsValid)
            {
                var user = _userService.GetCurrentUser(User.Identity.GetUserName());

                document.CreateBy = user;
                Document createdItem = _repository.Add(document);

                return RedirectToAction("View", new {id = createdItem.Id});
            }

            return View(document);
        }

        [Audit] 
        public ActionResult Edit(int? id)
        {
            if (id.HasValue == false)
            {
                return HttpNotFound();
            }

            Document document = _repository.Find(id.Value);

            if (document == null)
            {
                return HttpNotFound();
            }

            _cache.InvalidateCacheItem(id.Value);

            return View(document);
        }

        [Audit]
        [HttpPost]
        public ActionResult Edit(Document document)
        {
            if (ModelState.IsValid)
            {
                var user = _userService.GetCurrentUser(User.Identity.GetUserName());

                document.EditedBy = user;

                _repository.Update(document);

                _cache.InvalidateCacheItem(document.Id);

                return RedirectToAction("View", new {id = document.Id});
            }

            return View();
        }

        [Audit]
        public ActionResult Delete(int? id)
        {
            if (id.HasValue == false)
            {
                return HttpNotFound();
            }

            _cache.InvalidateCacheItem(id.Value);

            Document document = _repository.Table().FirstOrDefault(m => m.Id == id.Value);

            if (document == null)
            {
                return HttpNotFound();
            }
            var user = _userService.GetCurrentUser(User.Identity.GetUserName());

            document.DeletedBy = user;

            document.IsDeleted = true;

            _repository.Update(document);

            return RedirectToAction("Index");
        }

        [HttpPost]
        public FineUploaderResult UploadToPresentations(FineUpload upload, int? id)
        {
            if (id.HasValue == false)
            {
                return new FineUploaderResult(false, error: "id is null");
            }

            _cache.InvalidateCacheItem(id.Value);

            string guidFilename = AttachmentHelper.CreateGuidFilename(upload.Filename);

            string uploadPath = AttachmentHelper.GetUploadPath(guidFilename, _settings.DocumentsServerPath);

            string accessPath = AttachmentHelper.GetAccessPath(guidFilename, _settings.DocumentsAccessPath);
            try
            {
                upload.SaveAs(uploadPath);

                var attachment = new Attachment {Name = upload.Filename, Path = accessPath};

                Document document = _repository.Table().Include(x => x.Attachments).SingleOrDefault(x => x.Id == id.Value);

                if (document == null)
                {
                    throw new Exception("Announcement is null");
                }

                if (document.Attachments == null)
                {
                    document.Attachments = new Collection<Attachment>();
                }

                document.Attachments.Add(attachment);

                _repository.Update(document);

                string attachmentsHtml = RenderPartialViewToString("AttachmentList", document.Attachments);

                // the anonymous object in the result below will be convert to json and set back to the browser
                return new FineUploaderResult(true, new {extraInformation = 12345, attachmentsHtml, accessPath});
            }
            catch (Exception ex)
            {
                return new FineUploaderResult(false, error: ex.Message);
            }
        }
    }
}

Gvm/Views/Documents/Create.cshtml
@model Turkok.Model.Document

@{
    ViewBag.Title = "Yeni Döküman";
}
 
<aside class="right-side">

    <section class="content-header">
        <h1> Yeni Duyuru </h1>
    </section>


    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="well well-sm">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Description)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.PublishDate, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @(Html.Kendo().DatePicker()
                              .Name("PublishDate")
                              .Value(DateTime.Now.ToShortDateString())
                                    )
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Kaydet" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
</aside>

Gvm/Views/Documents/Edit.cshtml
@model Turkok.Model.Document

@{
    ViewBag.Title = "Duzenle";
}

<aside class="right-side">

    <section class="content-header">
        <h1> Duyuru Duzenle</h1>
    </section>


    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="well well-sm">

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        @Html.HiddenFor(model => model.Id)

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Description)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.PublishDate, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @(Html.Kendo().DatePicker()
                              .Name("PublishDate")
                              .Value(Model.PublishDate.ToShortDateString())
                                    )
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Kaydet" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }

                </div>
            </div>
        </div>
    </section>
</aside>

Gvm/Views/Documents/Index.cshtml
@{
    ViewBag.Title = "Dökümanlar";
}

@using Turkok.Model

<aside class="right-side">

    <section class="content-header">
        <h1>Dökümanlar</h1>
    </section>

    <section class="content">
        <div class="row box-danger">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">

                    </div>
                    <div class="box-body" style="padding: 10px;">
                        <div class="pull-left">
                            @Html.ActionLink("Yeni döküman", "Create", "Documents", null, new { @class = "btn btn-primary" })
                        </div>

                        <div class="clearfix"></div>
                        @(Html.Kendo().Grid<Document>()
              .Name("grid")
              .Columns(columns =>
              {
                  columns.Bound(p => p.Title).ClientTemplate("<a href='/Documents/View/#= Id#'>#=Title#</a>");
                  columns.Bound(p => p.PublishDate).Format("{0:dd/MM/yyyy}").Width(120);
                  columns.Bound(p => p.CreateBy).Width(120);
              })
              .Pageable(pageable => pageable.Refresh(true).PageSizes(true).ButtonCount(5))
              .Sortable()
              .Scrollable()
              .HtmlAttributes(new { style = "height:600px;" })
              .DataSource(dataSource => dataSource
                  .Ajax()
                  .PageSize(20)
                  .Events(events => events.Error("error_handler"))
                  .Model(model => model.Id(p => p.Id))
                  .Read(read => read.Action("Read", "Documents"))
              )
                        )
                    </div>

                    <div class="box-footer">

                    </div>
                </div>
            </div>
        </div>
    </section>
</aside>

<script type="text/javascript">
    function error_handler(e) {

        if (e.errors) {
            var message = "Errors:\n";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });

            alert(message);
        }
    }

</script>

Gvm/Views/Documents/View.cshtml
@using Microsoft.AspNet.Identity
@model Turkok.Model.Document

@{
    ViewBag.Title = @Model.Title;
}

<aside class="right-side">
    <section class="content-header">
        <h1>@Model.Title</h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive no-padding" style="margin-left: 10px;">
                        @Html.Raw(HttpUtility.HtmlDecode(Model.Description))<br />

                        <div class="pull-left">
                            <label class="label label-danger"><strong>Tarih : </strong>@Html.DisplayFor(model => model.DateCreated) </label> <br />
                            @*<label class="label label-primary"><strong>Kulanici :</strong> @Model.UserCreated</label> <br />*@
                        </div>
                    </div>
                    <hr />
                    <div>
                        <div> <i class="fa fa-files-o"></i>Eklentiler</div>

                        @{ Html.RenderPartial("Attachment");}

                        <br />
                        <div id="attachment_list">
                            @if (Model.Attachments != null)
                            {
                                @Html.Partial("AttachmentList", Model.Attachments)
                            }
                        </div>
                    </div>
                    
                    <div class="pull-right">
                        <div class="btn-group">
                            @Html.ActionLink("Duzenle", "Edit", "Documents", new { id = Model.Id }, new { @class = "btn btn-primary btn-sm" })
                            @Html.ActionLink("Sil", "Delete", "Documents", new { id = Model.Id }, new { @class = "btn btn-danger btn-sm", onclick = "return confirm('Are you sure you wish to delete this ?');" })
                            @Html.ActionLink("Dokumanlar", "Index", null, new { @class = "btn btn-info btn-sm" })
                        </div>
                    </div>
                    <div class="clearfix"></div>
                </div>
            </div>
        </div> 
    </section>
</aside>


<script>
    $(document).ready(function () {
        var manualuploader = $('#manual-fine-uploader').fineUploader({
            request: {
                endpoint: '/Documents/UploadToPresentations?id=@Model.Id'
            },
            template: "qq-template-manual-noedit",
            autoUpload: false
        }).on('complete', function (event, id, fileName, responseJSON) {
            if (responseJSON.success) {
                $('#attachment_list').html(responseJSON.attachmentsHtml);
            }
        });

        $('#triggerUpload').click(function () {
            manualuploader.fineUploader('uploadStoredFiles');
        });
    });
</script>