Gvm/Controllers/AnnouncementsController.cs
using System; 
using System.Collections.ObjectModel;
using System.Data.Entity;
using System.Linq;
using System.Net; 
using System.Web.Mvc;
using Gvm.Infra;
using Gvm.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNet.Identity; 
using Turkok.Core.Caching;
using Turkok.Core.Extensions;
using Turkok.Core.Mappers;
using Turkok.Core.Repository;
using Turkok.Core.Service; 
using Turkok.Core.Settings;
using Turkok.Model;
using Turkok.Model.FineUploader;

namespace Gvm.Controllers
{
    [Authorize]
    public class AnnouncementsController : MController
    { 
        private readonly IRepository<Announcement> _repository; 
        private readonly IApplicationSettings _settings;
        private readonly ICacheManager<int, Announcement> _cache;
        private readonly IUserService _userService;

        public AnnouncementsController(IRepository<Announcement> repository, 
            IApplicationSettings settings,
            ICacheManager<int, Announcement> cache,
            IUserService userService) 
        {
            _repository = repository; 
            _userService = userService;
            _settings = settings;
            _cache = cache;
        }

        [Audit]
        public ActionResult Index()
        {
            return View();
        }

        [Audit]
        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            var announcements = _repository.Table().Where(x => x.IsDeleted == false).OrderByDescending(x=>x.Id);

            return Json(announcements.ToDataSourceResult(request));
        }


        [Audit]
        public ActionResult Create()
        {   
            return View();
        }
         
        [HttpPost]
        [Audit]
        public ActionResult Create(Announcement announcement)
        {
            if (ModelState.IsValid)
            { 

                var user = _userService.GetCurrentUser(User.Identity.GetUserName());

                announcement.CreatedBy = user;

                Announcement instance = _repository.Add(announcement);

                return RedirectToAction("View", new { id = instance.Id });
            }

            return View(announcement);
        }

        [Audit]
        public ActionResult View(int? id)
        {
            if (id.HasValue == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Announcement announcement = _cache.Get(id.Value);

            if (announcement == null)
            { 
                announcement = _repository.Table().Include(a => a.Attachments).Include(u => u.CreatedBy).FirstOrDefault(m => m.Id == id.Value);

                if (announcement == null)
                {
                    return HttpNotFound();
                }

                _cache.Set(id.Value, announcement);
            }

            return View(announcement);
        }

        [Audit]
        public ActionResult Delete(int? id)
        {
            if (id.HasValue == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            _cache.InvalidateCacheItem(id.Value);

            Announcement announcement = _repository.Table().FirstOrDefault(u => u.Id == id.Value);

            if (announcement == null)
            {
                return HttpNotFound();
            }

            var user = _userService.GetCurrentUser(User.Identity.GetUserName());

            announcement.DeletedBy = user;

            announcement.IsDeleted = true;
            _repository.Update(announcement);

            return RedirectToAction("Index");
        }

        [Audit] 
        public ActionResult Edit(int? id)
        {
            if (id.HasValue == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            _cache.InvalidateCacheItem(id.Value);

            Announcement announcement = _repository.Table().Include(m => m.CreatedBy).FirstOrDefault(u => u.Id == id.Value);

            if (announcement == null)
            {
                return HttpNotFound();
            }

            return View(announcement);
        }

        [Audit] 
        [HttpPost]
        public ActionResult Edit(Announcement announcement)
        {
            if (ModelState.IsValid)
            {  
                var user = _userService.GetCurrentUser(User.Identity.GetUserName());
                announcement.EditedBy = user;

                announcement.DateEdited = DateTime.Now;

                Announcement instance = _repository.Update(announcement);

                return RedirectToAction("View", new { id = instance.Id });
            }

            return View(announcement);
        }
         
        [Audit]
        [HttpPost]
        public FineUploaderResult UploadToAnnouncement(FineUpload upload, int? id)
        {

            if (id.HasValue == false)
            {
                return new FineUploaderResult(false, error: "id is null");
            }

            _cache.InvalidateCacheItem(id.Value);

            var guidFilename = AttachmentHelper.CreateGuidFilename(upload.Filename);

            var uploadPath = AttachmentHelper.GetUploadPath(guidFilename, _settings.AnnouncementServerPath);

            var accessPath = AttachmentHelper.GetAccessPath(guidFilename, _settings.AnnouncementAccessPath);
            try
            {
                upload.SaveAs(uploadPath);

                var attachment = new Attachment { Name = upload.Filename, Path = accessPath };

                var announcement = _repository.Table().Include(x => x.Attachments).SingleOrDefault(x => x.Id == id.Value);

                if (announcement == null)
                {
                    throw new Exception("Announcement is null");
                }

                if (announcement.Attachments == null)
                {
                    announcement.Attachments = new Collection<Attachment>();
                }

                announcement.Attachments.Add(attachment);

                _repository.Update(announcement);

                var attachmentsHtml = RenderPartialViewToString("AttachmentList", announcement.Attachments);
                 
                return new FineUploaderResult(true, new { extraInformation = 12345, attachmentsHtml, accessPath });
            }
            catch (Exception ex)
            {
                return new FineUploaderResult(false, error: ex.Message);
            }
        }
    }
}

Gvm/Views/Announcements/Create.cshtml
@model Turkok.Model.Announcement

@{
    ViewBag.Title = "Yeni Duyuru";
}

<aside class="right-side">

    <section class="content-header">
        <h1> Yeni Duyuru </h1>
    </section>


    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="well well-sm">
                    @using (Html.BeginForm())
                    {
                        <div class="form-horizontal">
                            @Html.ValidationSummary(true)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Title)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Description, new{ @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Description)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.PublishDate, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @(Html.Kendo().DatePicker()
                                      .Name("PublishDate")
                                      .Value(DateTime.Now.ToShortDateString())
                                    )
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Yayinla" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
</aside>

Gvm/Views/Announcements/Edit.cshtml
@model Turkok.Model.Announcement

@{
    ViewBag.Title = "Düzenle";
}

<aside class="right-side">

    <section class="content-header">
        <h1> Duyuru Duzenle</h1>
    </section>


    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="well well-sm">

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true)
                            @Html.HiddenFor(model => model.Id)
                            @Html.HiddenFor(model => model.DateCreated)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Title, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextBoxFor(model => model.Title, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Title)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Description)
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.PublishDate, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @(Html.Kendo().DatePicker()
                              .Name("PublishDate")
                              .Value(Model.PublishDate.ToShortDateString())
                                    )
                                </div>
                            </div>


                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Kaydet" class="btn btn-primary" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
</aside>

Gvm/Views/Announcements/Index.cshtml
@{
    ViewBag.Title = "Duyurular";
}

@using Kendo.Mvc.UI
@using Thinktecture.IdentityModel.Authorization
@using Turkok.Model
@using Turkok.Model.Lookup

<aside class="right-side">

    <section class="content-header">
        <h1>Duyurular</h1>
    </section>

    <section class="content">
        <div class="row box-danger">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">

                    </div>
                    <div class="box-body" style="padding: 10px;">
                       
                        @if (ClaimsAuthorization.CheckAccess(Resources.DokumanlarActions.Edit, Resources.Duyurular))
                        {
                            <div class="well" style="padding-bottom: 20px;">
                                <a class="btn btn-primary" href="@Url.Action("Create", "Announcements")"><i class="fa  fa-plus-square-o"></i>&nbsp;&nbsp;Yeni Duyuru</a>
                            </div>
                        }

                        @(Html.Kendo().Grid<Announcement>()
                              .Name("grid")
                              .Columns(columns =>
                              {
                                  columns.Bound(p => p.Title).ClientTemplate("<a href='/Announcements/View/#= Id#'>#=Title#</a>");
                                  columns.Bound(p => p.PublishDate).Format("{0:dd/MM/yyyy}").Width(120);
                                  columns.Bound(p => p.CreatedBy).Width(120);
                              })
                              .Pageable(pageable => pageable.Refresh(true).PageSizes(true).ButtonCount(5))
                              .Sortable()
                              .Scrollable()
                              .HtmlAttributes(new { style = "height:600px;" })
                              .DataSource(dataSource => dataSource
                                  .Ajax()
                                  .PageSize(20)
                                  .Events(events => events.Error("error_handler"))
                                  .Model(model => model.Id(p => p.Id))
                                  .Read(read => read.Action("Read", "Announcements"))
                              )
                        )
                    </div>

                    <div class="box-footer">

                    </div>
                </div>
            </div>
        </div>
    </section>
</aside>

<script type="text/javascript">
    function error_handler(e) {

        if (e.errors) {
            var message = "Errors:\n";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });

            alert(message);
        }
    }

</script>

Gvm/Views/Announcements/View.cshtml
@using Thinktecture.IdentityModel.Authorization
@using Turkok.Model.Lookup
@model Turkok.Model.Announcement

@{
    ViewBag.Title = Model.Title;
}


@if (ClaimsAuthorization.CheckAccess(Resources.DuyurularActions.Edit, Resources.Duyurular))
{
    @Html.Partial("_View_EditMode", Model)
}
else if (ClaimsAuthorization.CheckAccess(Resources.DuyurularActions.View, Resources.Duyurular))
{
    @Html.Partial("_View_ViewMode", Model)
}

Gvm/Views/Announcements/_View_EditMode.cshtml
@using System.ServiceModel.Description
@model Turkok.Model.Announcement

<aside class="right-side">
    <section class="content-header">
        <h1>@Model.Title</h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive no-padding" style="margin-left: 10px;">
                        <div>
                            @Html.Raw(HttpUtility.HtmlDecode(Model.Description))<br />
                        </div>
                        <hr />
                        <div class="callout callout-info">
                            <div class="pull-left">
                                <strong>Yayınlama Zamanı:</strong> @Html.DisplayFor(model => model.PublishDate)<br />
                                @* <strong>Oluşturan:</strong> @Model.CreateBy.UserName*@
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <hr />
                        <div>
                            <div> <i class="fa fa-files-o"></i>Eklentiler</div>
                            @{ Html.RenderPartial("Attachment"); }
                            <div id="attachment_list">
                                @Html.Partial("AttachmentList", Model.Attachments)
                            </div>
                        </div>

                        <div class="pull-right">
                            <div class="btn-group">
                                @Html.ActionLink("Düzenle", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary btn-sm" })
                                @Html.ActionLink("Sil", "Delete", new { id = Model.Id }, new { @class = "btn btn-danger btn-sm", onclick = "return confirm('Are you sure you wish to delete this ?');" })
                                @Html.ActionLink("Duyurular", "Index", null, new { @class = "btn btn-info btn-sm" })
                            </div>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</aside>


<script>
    $(document).ready(function () {
        var manualuploader = $('#manual-fine-uploader').fineUploader({
            request: {
                endpoint: '/Announcements/UploadToAnnouncement?id=@Model.Id'
            },
            template: "qq-template-manual-noedit",
            autoUpload: false
        }).on('complete', function (event, id, fileName, responseJSON) {
            if (responseJSON.success) {
                $('#attachment_list').html(responseJSON.attachmentsHtml);
            }
        });

        $('#triggerUpload').click(function () {
            manualuploader.fineUploader('uploadStoredFiles');
        });
    });
</script>

Gvm/Views/Announcements/_View_ViewMode.cshtml
@using System.ServiceModel.Description
@model Turkok.Model.Announcement

<aside class="right-side">
    <section class="content-header">
        <h1>@Model.Title</h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-body table-responsive no-padding" style="margin-left: 10px;">
                        <div>
                            @Html.Raw(HttpUtility.HtmlDecode(Model.Description))<br />
                        </div>
                        <hr />
                        <div class="callout callout-info">
                            <div class="pull-left">
                                <strong>Yayınlama Zamanı:</strong> @Html.DisplayFor(model => model.PublishDate)<br />
                                @* <strong>Oluşturan:</strong> @Model.CreateBy.UserName*@
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <hr />
                        <div>
                            <div> <i class="fa fa-files-o"></i>Eklentiler</div>
                            <div id="attachment_list">
                                @Html.Partial("AttachmentList", Model.Attachments)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</aside>