Gvm/Controllers/KullanicilarController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Gvm.Infra;
using Gvm.Models;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Turkok.Core.Mappers;
using Turkok.Core.Repository;
using Turkok.Core.Service;
using Turkok.Model;

namespace Gvm.Controllers
{
    public class KullanicilarController : Controller
    {
        private readonly IUserService _userService;
        private UserManager<ApplicationUser> _userManager;
        private readonly IRepository<Sehir> _cityRepository;
        private readonly IMapper<ApplicationUser, ApplicationUser> _userMapper;

        public KullanicilarController(IUserService userService,
                                    UserManager<ApplicationUser> userManager,
                                    IRepository<Sehir> cityRepository,
                                    IMapper<ApplicationUser, ApplicationUser> userMapper)
        {
            _userService = userService;
            _userManager = userManager;
            _cityRepository = cityRepository;
            _userMapper = userMapper;
        }

        [Audit]
        public ActionResult Index()
        {
            return View();
        }

        [Audit]
        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            var kullanicilar = _userService.GetTable().Where(x => x.UserName.ToLower() != "admin@turkok.com");

            return Json(kullanicilar.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }

        public ActionResult ApproveUser(string username)
        {
            if (string.IsNullOrEmpty(username)) return HttpNotFound();

            var user = _userService.GetTable().FirstOrDefault(x => x.UserName == username);
            if (user == null) return HttpNotFound();

            var model = LoadUserModel(username);
            model.Roller = PopulateUserRoles();

            return View(model);
        }

        public ActionResult EditUser(string username)
        {
            if (string.IsNullOrEmpty(username)) return HttpNotFound();

            var user = _userService.GetTable().FirstOrDefault(x => x.UserName == username);
            if (user == null) return HttpNotFound();

            var model = LoadUserModel(username);
            model.Roller = PopulateUserRoles();
            //var userRoleId = string.IsNullOrEmpty(user.UserRole)
            //    ? ""
            //    : roller.Where(x => x.Text == user.UserRole).Select(y => y.Value).FirstOrDefault();

            
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ApproveUser(ApproveOrEditUserViewModel model)
        {
            if (string.IsNullOrEmpty(model.UserId)) return HttpNotFound();

            if (string.IsNullOrEmpty(model.SelectedRole))
            {
                ModelState.AddModelError("", "Kullanıcıyı aktif yapmak için bir rol seçmelisiniz.");

                model = LoadUserModel(model.UserName);
                model.Roller = PopulateUserRoles();

                return View(model);
            }

            _userManager.RemoveFromRoles(model.UserId, GetAllRoles());
            _userManager.AddToRole(model.UserId, model.SelectedRole);

            var user = _userService.Find(model.UserId);
            user.UserRole = model.SelectedRole;
            user.Active = true;

            _userService.Update(user);

            return RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditUser(ApproveOrEditUserViewModel model)
        {
            if (string.IsNullOrEmpty(model.UserId)) return HttpNotFound();

            _userManager.RemoveFromRoles(model.UserId, GetAllRoles());
            var user = _userService.Find(model.UserId);

            if (string.IsNullOrEmpty(model.SelectedRole))
            {
                user.UserRole = null;
                user.Active = false;
            }
            else
            {
                _userManager.AddToRole(model.UserId, model.SelectedRole);

                user.UserRole = model.SelectedRole;
                user.Active = true;
            }
            
            _userService.Update(user);

            return RedirectToAction("Index");
        }

        #region Helpers
        private ApproveOrEditUserViewModel LoadUserModel(string username)
        {
            if (string.IsNullOrEmpty(username)) return null;

            var user = _userService.GetTable().FirstOrDefault(x => x.UserName == username);

            if (user == null) return null;

            return new ApproveOrEditUserViewModel
            {
                UserId = user.Id,
                Active = user.Active,
                UserName = user.UserName,
                AdiSoyadi = user.FullName,
                BasvuruTarihi = user.DateCreated,
                SelectedRole = user.UserRole,
                NotWorkingForUnit = user.NotWorkingForUnit
            };
        }
        private IEnumerable<SelectListItem> PopulateUserRoles()
        {
            var roles = GetAllRoles();
            
            return roles.Select(role => new SelectListItem { Text = role, Value = role }).ToList();
        }
        private string[] GetAllRoles()
        {
            using (var context = new DataContext())
            {
                return context.Roles.OrderBy(x => x.Name).Select(y => y.Name).ToArray();
            }
        }
        #endregion
    }
}

Gvm/Views/Kullanicilar/ApproveUser.cshtml
@model Gvm.Models.ApproveOrEditUserViewModel
@{
    ViewBag.Title = "Kullanıcıyı Aktif Yap";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<aside class="right-side">

    <section class="content-header">
        <h1> Kullanıcıyı Aktif Yap </h1>
    </section>
    
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                @if (ViewData.ModelState.IsValid == false)
                {
                    <div class="alert alert-danger alert-dismissable">
                        <i class="fa fa-ban"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        @Html.ValidationSummary(true)
                        @Html.ValidationMessage("Error")
                    </div>
                }
                
                <div class="well well-sm">
                    <div class="form-horizontal">
                        <dl class="col-md-11 col-md-offset-1">
                            <dt>
                                @Html.DisplayNameFor(model => model.UserName)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.UserName)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.AdiSoyadi)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.AdiSoyadi)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.BasvuruTarihi)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.BasvuruTarihi)
                            </dd>
                            
                            <dt>
                                @Html.DisplayNameFor(model => model.NotWorkingForUnit)
                            </dt>

                            <dd>
                                @if (Model.NotWorkingForUnit)
                                {
                                    <p>Hayır</p>
                                }
                                else
                                {
                                    <p>Evet</p>
                                }
                            </dd>
                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model => model.UserId)
                            @Html.HiddenFor(model => model.UserName)

                            <div class="form-group">
                                @Html.LabelFor(model => model.Roller, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(x => x.SelectedRole, Model.Roller, "- Seçiniz -")
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Aktif Yap" class="btn btn-default" />
                                </div>
                            </div>
                        }
                    </div>

                </div>
            </div>
        </div>
    </section>
</aside>

Gvm/Views/Kullanicilar/EditUser.cshtml
@model Gvm.Models.ApproveOrEditUserViewModel
@{
    ViewBag.Title = "Kullanıcıyı Düzelt";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<aside class="right-side">

    <section class="content-header">
        <h1> Kullanıcıyı Düzelt </h1>
    </section>

    <section class="content">
        <div class="row">
            <div class="col-md-12">
                @if (ViewData.ModelState.IsValid == false)
                {
                    <div class="alert alert-danger alert-dismissable">
                        <i class="fa fa-ban"></i>
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                        @Html.ValidationSummary(true)
                        @Html.ValidationMessage("Error")
                    </div>
                }

                <div class="well well-sm">
                    <div class="form-horizontal">
                        <dl class="col-md-11 col-md-offset-1">
                            <dt>
                                @Html.DisplayNameFor(model => model.UserName)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.UserName)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.AdiSoyadi)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.AdiSoyadi)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.BasvuruTarihi)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.BasvuruTarihi)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.SelectedRole)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.SelectedRole)
                            </dd>
                            
                            <dt>
                                @Html.DisplayNameFor(model => model.NotWorkingForUnit)
                            </dt>

                            <dd>
                                @if (Model.NotWorkingForUnit)
                                {
                                    <p>Çalışmıyor</p>
                                }
                                else
                                {
                                    <p>Çalışıyor</p>
                                }
                            </dd>
                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()
                            @Html.HiddenFor(model => model.UserId)
                            @Html.HiddenFor(model => model.UserName)
                            
                            <div class="form-group">
                                @Html.LabelFor(model => model.Roller, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.DropDownListFor(x => x.SelectedRole, Model.Roller, "Pasif Kullanıcı")
                                </div>
                            </div>
                            
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Kaydet" class="btn btn-default" />
                                </div>
                            </div>
                        }
                    </div>

                </div>
            </div>
        </div>
    </section>
</aside>

Gvm/Views/Kullanicilar/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using Kendo.Mvc.UI
@using Turkok.Model
@using Gvm.Infra

<aside class="right-side">

    <section class="content-header">
        <h1>Basvurular</h1>
    </section>

    <section class="content">
        <div class="row box-danger">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">

                    </div>
                    <div class="box-body" style="padding: 10px;">

                        @*<div class="well" style="padding-bottom: 20px;">
                            <a class="btn btn-default" href="@Url.Action("CreateUser", "Kullanicilar")"><i class="fa  fa-plus"></i>&nbsp;&nbsp;Yeni Kullanıcı</a>
                        </div>*@

                        @(Html.Kendo().Grid<ApplicationUser>()
                        .Name("grid")
                        .Columns(columns =>
                            {
                                columns.Bound(p => p.UserName).Width(220).Title("Kullanıcı Adı");
                                columns.Bound(p => p.DateCreated).Width(220)
                                       .ClientTemplate("#= kendo.toString(DateCreated, 'g') #").Title("Başvuru Tarihi");
                                columns.Bound(p => p.FullName).Width(220).Title("Adı-Soyadı");
                                columns.Bound(p => p.UserRole).Width(120).Title("Rolü");
                                columns.Bound(p => p.Active).Width(120)
                                       .ClientTemplate("#if(Active){# <a class='btn btn-default' href='" + Url.Action("EditUser", "Kullanicilar") + "?username=#:UserName#'><i class='fa fa-pencil'></i>&nbsp;&nbsp;Rolü Düzelt</a> #}" +
                                                       "else       {# <a class='btn btn-primary' href='" + Url.Action("ApproveUser", "Kullanicilar") + "?username=#:UserName#'><i class='fa fa-play-circle'></i>&nbsp;&nbsp;Onayla</a>#}#").Title("");
                            })
                        .Pageable(pageable => pageable.Refresh(true).PageSizes(true).ButtonCount(5))
                        .Sortable()
                        .Scrollable()
                        .HtmlAttributes(new { style = "height:430px;" })
                        .DataSource(dataSource => dataSource
                            .Ajax()
                            .PageSize(20)
                                .Events(events => events.Error("error_handler"))
                                .Model(model => model.Id(p => p.Id))
                                .Read(read => read.Action("Read", "Kullanicilar"))
                        )
                        )

                    </div>

                    <div class="box-footer">

                    </div>
                </div>
            </div>
        </div>
    </section>
</aside>

<script type="text/javascript">

    function error_handler(e) {
        if (e.errors) {
            var message = "Errors:\n";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });

            alert(message);
        }
    }
</script>