Gvm/Controllers/ActionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Routing;
using System.Web.UI.WebControls;
using Gvm.Infra;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Thinktecture.IdentityModel.Authorization.Mvc;
using Turkok.Core.Repository;
using Turkok.Model.Lookup;
using Action = Turkok.Model.Action;
using Unit = Turkok.Model.Unit;

namespace Gvm.Controllers
{
    [ClaimsAuthorize(Resources.ActionActions.View, Resources.Actions)]
    public class ActionController : MController
    {
        private readonly IRepository<Action> _repository;
        private readonly IRepository<Unit> _unitRepository; 

        public ActionController(IRepository<Action> repository, IRepository<Unit> unitRepository)
        {
            _repository = repository;
            _unitRepository = unitRepository;
        }

        [Audit]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            IOrderedQueryable<Action> actions = _repository.Table().OrderByDescending(x => x.StartDate);

            return Json(actions.ToDataSourceResult(request), JsonRequestBehavior.AllowGet);
        }
        public ActionResult Create()
        {
            PopulateUnitsDropDownList();
            return View();
        }

        [Audit]
        [HttpPost]
        public ActionResult Create(Action model)
        {
            if (ModelState.IsValid)
            {
                Action createdItem = _repository.Add(model);
                return RedirectToAction("Index");
                //return RedirectToAction("View", new { id = createdItem.Id });
            }

            return View(model);
        }
        private void PopulateUnitsDropDownList(object selectedUnit = null)
        {
            var unitQuery = _unitRepository.Table().OrderBy(u => u.Name);
            ViewBag.DeptChargedId = new SelectList(unitQuery, "Id", "Name", selectedUnit);
        }

        public ActionResult Add(int parentId)
        {
            PopulateUnitsDropDownList();
            ViewBag.ParentId = parentId;
            return View();
        }

        [Audit]
        public ActionResult View(int? id)
        {
            if (id.HasValue == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Action action = _repository.Table().FirstOrDefault(m => m.Id == id.Value);
            if (action == null)
            {
                return HttpNotFound();
            }

            return View(action);
        }

        [Audit]
        public ActionResult Edit(int? id)
        {
            if (id.HasValue == false)
            {
                return HttpNotFound();
            }

            Action action = _repository.Find(id.Value);

            if (action == null)
            {
                return HttpNotFound();
            }

            PopulateUnitsDropDownList(action.DeptChargedId);
            return View(action);
        }

        [Audit]
        [HttpPost]
        public ActionResult Edit(Action model)
        {
            if (ModelState.IsValid)
            {
                _repository.Update(model);

                return RedirectToAction("View", new { id = model.Id });
            }

            return View();
        }


        [Audit]
        public ActionResult Delete(int? id)
        {
            if (id.HasValue == false)
            {
                return HttpNotFound();
            }

            Action action = _repository.Table().FirstOrDefault(m => m.Id == id.Value);

            if (action == null)
            {
                return HttpNotFound();
            }

            _repository.Remove(action);

            return RedirectToAction("Index");
        }

    }
}

Gvm/Controllers/TargetController.cs
using System;
using System.Collections.ObjectModel;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using Gvm.Infra;
using Kendo.Mvc.Extensions;
using Kendo.Mvc.UI;
using Thinktecture.IdentityModel.Authorization.Mvc;
using Turkok.Core.Repository;
using Turkok.Model;
using Turkok.Model.Lookup;
using Action = Turkok.Model.Action;

namespace Gvm.Controllers
{
    [ClaimsAuthorize(Resources.TargetActions.View, Resources.Targets)]
    public class TargetController : MController
    {
        private readonly IRepository<Target> _repository;
        private readonly IRepository<Action> _actionRepository;

        public TargetController(IRepository<Target> repository, IRepository<Action> actionRepository)
        {
            _repository = repository;
            _actionRepository = actionRepository;
        }
        [Audit]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Read([DataSourceRequest] DataSourceRequest request)
        {
            IOrderedQueryable<Target> targets = _repository.Table().OrderByDescending(x => x.Id);

            return Json(targets.ToDataSourceResult(request));
        }
        public ActionResult Create()
        {
            return View();
        }

        [Audit]
        [HttpPost]
        public ActionResult Create(Target model)
        {
            if (ModelState.IsValid)
            {
                Target createdItem = _repository.Add(model);
                return RedirectToAction("Index");
                //return RedirectToAction("View", new { id = createdItem.Id });
            }

            return View(model);
        }

        [Audit]
        public ActionResult View(int? id)
        {
            if (id.HasValue == false)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            Target target = _repository.Table().Include(a => a.Actions).FirstOrDefault(m => m.Id == id.Value);
            if (target == null)
            {
                return HttpNotFound();
            }
            
            return View(target);
        }

        [Audit]
        [HttpPost]
        public ActionResult AddAction(int parentId, Turkok.Model.Action model)
        {
            if (ModelState.IsValid)
            {
                var target = _repository.Find(parentId);
                if(target.Actions == null)
                    target.Actions = new Collection<Action>();
                target.Actions.Add(model);
                _repository.Update(target);
                return RedirectToAction("View", new { id = parentId });
            }
            ViewBag.ParentId = parentId;
            return RedirectToAction("Add", "Action", new {parentId});
        }

        [Audit]
        public ActionResult Edit(int? id)
        {
            if (id.HasValue == false)
            {
                return HttpNotFound();
            }

            Target target = _repository.Find(id.Value);

            if (target == null)
            {
                return HttpNotFound();
            }

            return View(target);
        }

        [Audit]
        [HttpPost]
        public ActionResult Edit(Target target)
        {
            if (ModelState.IsValid)
            {
                _repository.Update(target);

                return RedirectToAction("View", new { id = target.Id });
            }

            return View();
        }


        [Audit]
        public ActionResult Delete(int? id)
        {
            if (id.HasValue == false)
            {
                return HttpNotFound();
            }

            Target target = _repository.Table().Include(m => m.Actions).FirstOrDefault(m => m.Id == id.Value);

            if (target == null)
            {
                return HttpNotFound();
            }

            var actions = target.Actions.ToList();

            for(int i=0; i<actions.Count; i++)
            {
                _actionRepository.Remove(actions[i]);
                target.Actions.Remove(actions[i]);
            }

            _repository.Remove(target);

            return RedirectToAction("Index");
        }
    }
}

Gvm/Views/Action/Add.cshtml
@model Turkok.Model.Action

@{
    ViewBag.Title = "Yeni Faaliyet";
}

<h2>Yeni Faaliyet</h2>

<aside class="right-side">

    <section class="content-header">
        <h1> Yeni Faaliyet </h1>
    </section>


    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="well well-sm">
                    @using (Html.BeginForm("AddAction", "Target", new{parentId = ViewBag.ParentId}, FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.ActionId, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ActionId, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ActionId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            @*
                                <div class="form-group">
                                    @Html.LabelFor(model => model.DeptCharged, htmlAttributes: new { @class = "control-label col-md-2" })
                                    <div class="col-md-10">
                                        @Html.EditorFor(model => model.DeptCharged, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.DeptCharged, "", new { @class = "text-danger" })
                                    </div>
                                </div>
                            *@

                            <div class="form-group">
                                <label class="control-label col-md-2" for="DeptChargedId">Sorumlu Birim</label>
                                <div class="col-md-10">
                                    @Html.DropDownList("DeptChargedId", null, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.DeptChargedId, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group">
                                @Html.LabelFor(model => model.SupportUnit, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.SupportUnit, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.SupportUnit, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Collaborators, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Collaborators, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Collaborators, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.IndicatorName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.IndicatorName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.IndicatorName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.IndicatorCurrentState, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.IndicatorCurrentState, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.IndicatorCurrentState, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.IndicatorObjective, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.IndicatorObjective, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.IndicatorObjective, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.IndicatorOccurrenceValue, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.IndicatorOccurrenceValue, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.IndicatorOccurrenceValue, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.StartDate, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @(Html.Kendo().DatePicker()
                                          .Name("StartDate")
                                          .Value(DateTime.Now.ToShortDateString())
                                    )
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.EndDate, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @(Html.Kendo().DatePicker()
                              .Name("EndDate")
                              .Value(DateTime.Now.ToShortDateString())
                                    )
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Description)
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Kaydet" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
</aside>

Gvm/Views/Action/Create.cshtml
@model Turkok.Model.Action

@{
    ViewBag.Title = "Yeni Faaliyet";
}

<h2>Yeni Faaliyet</h2>

<aside class="right-side">

    <section class="content-header">
        <h1> Yeni Faaliyet </h1>
    </section>


    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="well well-sm">
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            <div class="form-group">
                                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                            <div class="form-group">
                                @Html.LabelFor(model => model.ActionId, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.ActionId, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.ActionId, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                            @*
                            <div class="form-group">
                                @Html.LabelFor(model => model.DeptCharged, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.DeptCharged, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.DeptCharged, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            *@

                            <div class="form-group">
                                <label class="control-label col-md-2" for="DeptChargedId">Sorumlu Birim</label>
                                <div class="col-md-10">
                                    @Html.DropDownList("DeptChargedId", null, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.DeptChargedId, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class="form-group">
                                @Html.LabelFor(model => model.SupportUnit, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.SupportUnit, new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.SupportUnit, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                            <div class="form-group">
                                @Html.LabelFor(model => model.Collaborators, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Collaborators, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Collaborators, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                            <div class="form-group">
                                @Html.LabelFor(model => model.IndicatorName, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.IndicatorName, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.IndicatorName, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                            <div class="form-group">
                                @Html.LabelFor(model => model.IndicatorCurrentState, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.IndicatorCurrentState, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.IndicatorCurrentState, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                            <div class="form-group">
                                @Html.LabelFor(model => model.IndicatorObjective, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.IndicatorObjective, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.IndicatorObjective, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.IndicatorOccurrenceValue, htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.IndicatorOccurrenceValue, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.IndicatorOccurrenceValue, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            
                            <div class="form-group">
                                @Html.LabelFor(model => model.StartDate, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @(Html.Kendo().DatePicker()
                                          .Name("StartDate")
                                          .Value(DateTime.Now.ToShortDateString())
                                          )
                                </div>
                            </div>
                            
                            <div class="form-group">
                                @Html.LabelFor(model => model.EndDate, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @(Html.Kendo().DatePicker()
                              .Name("EndDate")
                              .Value(DateTime.Now.ToShortDateString())
                                    )
                                </div>
                            </div>

                            <div class="form-group">
                                @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.Description)
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Kaydet" class="btn btn-default" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </section>
</aside>

Gvm/Views/Action/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using Kendo.Mvc.UI

<aside class="right-side">
    <section class="content-header">
        <h1>Faaliyetler</h1>
    </section>
    <section class="content">
        <div class="row box-danger">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                    </div>
                    <div class="box-body" style="padding: 10px;">
                        <div class="pull-left">
                            @Html.ActionLink("Yeni Faaliyet", "Create", "Action", null, new { @class = "btn btn-primary" })
                        </div>
                        <div class="clearfix"></div>
                        @(Html.Kendo().Grid<Turkok.Model.Action>()
                        .Name("grid")
                        .Columns(columns =>
                        {
                            columns.Bound(p => p.Name).Width(220).Title("Faaliyet Adı").ClientTemplate("<a href='/Action/View/#= Id#'>#=Name#</a>");
                            columns.Bound(p => p.ActionId).Width(220).Title("Faaliyet No");
                            columns.Bound(p => p.DeptCharged.Name).Width(220).Title("Sorumlu Birim");
                            columns.Bound(p => p.SupportUnit).Width(220).Title("Destek Birim");
                            columns.Bound(p => p.Collaborators).Width(220).Title("İşbirliği Yapılacak Kurum ve Kuruluşlar");
                            columns.Bound(p => p.IndicatorName).Width(220).Title("Gösterge Adı");
                            columns.Bound(p => p.IndicatorCurrentState).Width(220).Title("Gösterge Mevcut Durumu");
                            columns.Bound(p => p.IndicatorObjective).Width(220).Title("2014 Yılı Gösterge Hedefi");
                            columns.Bound(p => p.IndicatorOccurrenceValue).Width(220).Title("Gösterge Gerçekleşme Değeri");
                            columns.Bound(p => p.StartDate).Format("{0:dd-MM-yyyy}").Width(150).Title("Başlangıç Zamanı");
                            columns.Bound(p => p.EndDate).Format("{0:dd-MM-yyyy}").Width(120).Title("Bitiş Zamanı");
                            columns.Bound(p => p.Description).Width(220).Title("Açıklama");
                         })
                        .Pageable(pageable => pageable.Refresh(true).PageSizes(true).ButtonCount(5))
                        .Sortable()
                        .Scrollable()
                        .HtmlAttributes(new { style = "height:430px;" })
                        .DataSource(dataSource => dataSource
                            .Ajax()
                            .PageSize(20)
                                .Events(events => events.Error("error_handler"))
                                .Model(model => model.Id(p => p.Id))
                                .Read(read => read.Action("Read", "Action"))
                        )
                        )
                    </div>
                    <div class="box-footer">
                    </div>
                </div>
            </div>
        </div>
    </section>
</aside>
<script type="text/javascript">

    function error_handler(e) {
        if (e.errors) {
            var message = "Errors:\n";
            $.each(e.errors, function (key, value) {
                if ('errors' in value) {
                    $.each(value.errors, function () {
                        message += this + "\n";
                    });
                }
            });

            alert(message);
        }
    }
</script>